### ISSUE TITLE
import to eclipse

### ISSUE THREAD

**Issue by happy0191** [lukinf/SAPUI5-OData-Tree#1]
Hi,
first of all thank you for your sharing. Could you explain how can i import to this project to eclipse.

**Comment by lukinf** [comment]
Hi,  
1.)  In Eclipse you should create an new Empty project: File->New->Project->General->Project 
2.) Download or clone project from GitHub
3.) On previously created project (Right click): File->Import->General->From directory

**Comment by happy0191** [comment]
https://prnt.sc/q72250

its looking like that how can i run ?

how can i configure this?

https://prnt.sc/q722q2

**Comment by lukinf** [comment]
Hi,
but this is not issue. You can use standard Eclipse and web server(Apache, NGINX, IIS...) as you want ;-)

**Comment by happy0191** [comment]
I mean, 
when i want to run own app, i can select like this.
https://prnt.sc/q74jty
but when i want to run yours app i can not select web app preview.

sorry i am newly at eclipse editor.  :)

**Comment by lukinf** [comment]
Here, you can find out some documentation:
https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.stardust.docs.wst%2Fhtml%2Fwst-integration%2Fconfiguration.html
